version: "3.8"
services:
  frontend:
    image: node:16
    container_name: frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: bash -c "npm install -g npm@9.8.1 && npm run build && npm run start"
    ports:
      - "5173:5173"

  backend:
    image: rust:1.67-slim
    container_name: backend
    working_dir: /app/backend
    volumes:
      - ./.env:/app/backend/.env
      - ./target/release:/app/backend
      - ./files:/app/files
      - ./frontend/favicon.ico:/app/backend/favicon.ico
    command: bash -c "mkdir -p ./files/anon && ./backend"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: